server:
  port: 8081
  servlet:
    context-path: /user-service


#  8081/user-service/api/v1


spring:
  application:
    name: user-service



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


      spring:
        datasource:
          url: jdbc:mysql://localhost:3306/user_service_db
          username: root
          password: Ijse@123
